server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  config:
    import: "optional:configserver:"

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    gc-warnings: true
