server:
  port: 8080

spring:
  main:
    banner-mode: "off"

  cloud:
    config:
      enabled: false

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: true
      bandcamp: true
